services:
  fiap-food-preparation:
    image: ghcr.io/thallis-andre/fiap-food-preparation:latest
    build:
      context: ..
      args:
        target: 'fiap-food-preparation'
    restart: 'on-failure'
    environment:
      NODE_ENV: 'development'
      APP_NAME: 'FiapFoodPreparation'
      APP_DESCRIPTION: 'Preparations Component for Fiap Food'
      APP_VERSION: '1.0.0'
      PORT: '3000'
      LOG_LEVEL: 'debug'
      LOG_FORMAT: 'pretty' # pretty | json
      TRAFFIC_INSPECTION_HTTP: 'all' # inbound|outbound|all|none
      TRAFFIC_INSPECTION_AMQP: 'all' # inbound|outbound|all|none
      ROUTE_PREFIX: ''
      POSTGRES_URL: 'postgresql://postgres:fiapfood@postgres:5432/postgres?ApplicationName=FiapFoodPreparation'
      AMQP_URL: 'amqp://fiapfood:fiapfood@rabbitmq:5672'
    command: sh -c "sleep 10 && npm run start:prod"
    ports:
      - 3000:3000
    depends_on:
      - postgres
      - rabbitmq
  postgres:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: fiapfood
    ports:
      - 5432:5432
  mongodb:
    image: ghcr.io/thallis-andre/mongodbrs:6
    build:
      context: .
      dockerfile: ./Dockerfile.mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'fiapfood'
      MONGO_INITDB_ROOT_PASSWORD: 'fiapfood'
    command: 'mongod --replSet rs0 --keyFile /opt/.keyfile/keyfile --bind_ip_all'
    ports:
      - 27017:27017
  mongodb_init:
    image: mongo:6
    restart: 'on-failure'
    depends_on: [mongodb]
    command: >-
      sh -c "sleep 10 && mongosh -u fiapfood -p fiapfood --host mongodb:27017 --eval 'rs.initiate({
        \"_id\":\"rs0\",
        "members":[
          {
            \"_id\": 0,
            \"host\":\"mongodb:27017\",
          },
        ]
      })' && if [ $(mongosh -u fiapfood -p fiapfood --quiet --host mongodb:27017 --eval 'rs.status().ok') -eq 1 ]; then exit 0; else exit 1; fi"
  rabbitmq:
    image: ghcr.io/thallis-andre/rabbitmq:3-management-delayed
    build:
      context: .
      dockerfile: ./Dockerfile.rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: 'fiapfood'
      RABBITMQ_DEFAULT_PASS: 'fiapfood'
    ports:
      - 5672:5672
      - 15672:15672
