name: FiapFoodPreparation - CICD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-container:
    name: 'Build Application Container'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login no GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          build-args: |
            target=fiap-food-preparation
          tags: |
            ghcr.io/thallis-andre/fiap-food-preparation:latest
            ghcr.io/thallis-andre/fiap-food-preparation:v${{ github.run_number }}

  # deploy:
  #   name: 'Deploy Application'
  #   runs-on: ubuntu-latest
  #   needs: [build-container]
  #   environment: 'production'
  #   if: github.ref == 'refs/heads/main' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Configure AWS
  #       uses: aws-actions/configure-aws-credentials@v4
  #       with:
  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #         aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
  #         aws-region: us-east-1
  #     - name: Configure Kubectl
  #       run: aws eks update-kubeconfig --name fiap-food-k8s
  #     - name: Apply K8S
  #       run: |
  #         kubectl apply -f k8s/app.deployment.yaml
  #         kubectl rollout restart deployment/fiap-food-preparation